version: '3.8'
services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-container
    volumes:
      - ../:/workspace
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: sleep infinity  
    
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=bigred
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
    driver: local
