version: '3.8'
services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-container
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    networks:
      - app-network

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container
    environment:
      - SA_PASSWORD=YourPassword123
      - ACCEPT_EULA=Y
      - DB_NAME=mydb
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql-data:/var/opt/mssql

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
    driver: local
